trigger:
  branches:
    include:
      - main  # Trigger on changes to the main branch

pool:
  name: 'Default'  # Ensure you're using an agent that has Docker installed

variables:
  dockerRegistryServiceConnection: 'DockerConnection1'  # Docker Hub service connection
  imageName: 'abhishek1231/hoopstats'  # Docker Hub repository
  imageTag: '1.1'  # Tag for the Docker image

steps:
# Step to log in to Docker Hub
- task: Docker@2
  displayName: 'Log in to Docker Hub'
  inputs:
    containerRegistry: $(dockerRegistryServiceConnection)

# Step to check Docker availability (optional, for debugging)
- script: |
    docker --version
    docker info
  displayName: 'Check Docker Version and Info'

# Step to set up Docker Buildx
- script: |
    docker buildx create --use --name multi-builder
    docker buildx inspect --bootstrap
  displayName: 'Set up Docker Buildx'

# Step to build and push the Docker image with Buildx
- script: |
    docker buildx build \
      --platform linux/amd64,linux/arm64 \
      -t abhishek1231/hoopstats:1.1 \
      --push .
  displayName: 'Build and Push Multi-Platform Docker Image'

- script: |
    docker system prune -af
  displayName: 'Clean up Docker system after build'

# Deploy to Azure App Service
- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'SystemAssignedConnection'
    appName: 'HoopStats'
    containers: 'abhishek1231/hoopstats:1.1'


