trigger:
  branches:
    include:
      - main  

pool:
  name: 'Default'

variables:
  dockerRegistryServiceConnection: 'HoopStats'  
  imageName: 'abhishek1231/hoopstats' 
  imageTag: '1.1'  

steps:
- task: Docker@2
  displayName: 'Log in to Docker Hub'
  inputs:
    containerRegistry: $(dockerRegistryServiceConnection)

- script: |
    docker buildx create --use --name multi-builder
    docker buildx inspect --bootstrap
  displayName: 'Set up Docker Buildx'

- script: |
    docker buildx build \
      --platform linux/amd64,linux/arm64 \
      -t $(imageName):$(imageTag) \
      --push .
  displayName: 'Build and Push Multi-Platform Docker Image'
