trigger:
  branches:
    include:
      - main  # Trigger on changes to the main branch

pool:
  name: 'Default'

steps:
# Step to build and push Docker image to Docker Hub
- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    containerRegistry: 'DockerConnection'  # Docker Hub service connection
    repository: 'abhishek1231/hoopstats'  # Docker Hub repository name (e.g., 'abhishek1231/hoopstats')
    command: buildAndPush  # Command to build and push the Docker image
    Dockerfile: '**/Dockerfile'  # Path to Dockerfile in the repository
    tags: |
      '1.1'
 