trigger:
  branches:
    include:
      - main  # Trigger on changes to the main branch

pool:
  name: 'Default'

variables:
  dockerRegistryServiceConnection: 'HoopStats'  # Replace with your Docker Hub service connection name
  imageName: 'abhishek1231/hoopstats'  # Docker Hub repository name (without version/tag)
  imageTag: '1.1'  # Combine version with the build ID for tagging

steps:
# Log in to Docker Hub
- task: Docker@2
  displayName: 'Log in to Docker Hub'
  inputs:
    containerRegistry: $(dockerRegistryServiceConnection)

# Set up Docker Buildx
- script: |
    docker buildx create --use --name multi-builder
    docker buildx inspect --bootstrap
  displayName: 'Set up Docker Buildx'

# Build and Push Multi-Platform Docker Image
- script: |
    docker buildx build \
      --platform linux/amd64,linux/arm64 \
      -t $(imageName):$(imageTag) \
      --push .
  displayName: 'Build and Push Multi-Platform Docker Image'
